"""добавлена модель Vacancy

Revision ID: 007be10c13ba
Revises: 7b52c6ce6640
Create Date: 2025-08-25 10:32:47.489472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007be10c13ba'
down_revision: Union[str, None] = '7b52c6ce6640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vacancies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'user_id')
    # ### end Alembic commands ###
