"""добавлена поле hh_link в модель Vacancy

Revision ID: e00bf3593210
Revises: 007be10c13ba
Create Date: 2025-08-28 19:34:12.422849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00bf3593210'
down_revision: Union[str, None] = '007be10c13ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('hh_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'hh_link')
    # ### end Alembic commands ###
